apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sigstore-tekton
  namespace: openshift-operators
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
